version: "3.1"
services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network

  hyper-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyper-task-manager
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - hyper-task-manager-network
    depends_on:
      - mongodb

volumes:
  mongo-data:

networks:
  hyper-task-manager-network:

# Install curl
#  RUN apt-get update -y && apt-get install curl -y
# $ docker-compose up --build hyper-service

# Stop the services, delete containers, networks, and volumes;
# $ docker-compose down -v
# Remove the hyper-service image from the system.
# $ docker images
# $ docker rmi e3a05e3b288c